[project]
name = 'Exam-Results-Verification-Contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Exam-Results-Verification-Contract]
path = 'contracts/Exam-Results-Verification-Contract.clar'
clarity_version = 3
epoch = 3.1
[contracts.Certificate-Badge-System]
path = 'contracts/Certificate-Badge-System.clar'
clarity_version = 3
epoch = 3.1
[contracts.Academic-Reputation-System]
path = 'contracts/Academic-Reputation-System.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
